spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/fintech_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Wkdtldhs23@@
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# src/main/resources/application.yml
server:
  port: 8080

kis:
  app-key: "발급받은_APP_KEY"
  app-secret: "발급받은_APP_SECRET"
  # 모의투자: https://openapivts.koreainvestment.com:29443
  base-url: "https://openapi.koreainvestment.com:9443"